### Create a new user
POST http://localhost:8000/api/users/create
Content-Type: application/json

{
  "username": "testuser1",
  "email": "testuser1@gmail.com",
  "password_hash": "hashedpassword",
  "study_goal": 2,
  "is_online": true,
  "created_at": "2025-05-01T10:00:00"
}

### Get all users
GET http://localhost:8000/api/users

### Get user by ID
GET http://localhost:8000/api/users/2

### Get user subjects
GET http://localhost:8000/api/users/2/subjects

### Get user friends
GET http://localhost:8000/api/users/2/friends

### Get user's online friends
GET http://localhost:8000/api/users/2/friends/online

### Get user's friend requests
GET http://localhost:8000/api/users/2/friends/requests

### Get user posts
GET http://localhost:8000/api/users/2/posts

### Get user analytics
GET http://localhost:8000/api/users/2/analytics

### Get Feed
###
POST http://localhost:8000/api/users/feed
Content-Type: application/json

{
  "user_id": 1,
  "page": 1,
  "limit": 10
}

### Update a user
PATCH http://localhost:8000/api/users/2
Content-Type: application/json

{
  "username": "updateduser",
  "email": "updateduser@gmail.com",
  "study_goal": 5
}



### Delete a user
DELETE http://localhost:8000/api/users/4

### Send a friend request
POST http://localhost:8000/api/users/2/friends/4/request

### Accept a friend request
POST http://localhost:8000/api/users/2/friends/4/accept

### Decline a friend request
DELETE http://localhost:8000/api/users/4/friends/2/decline

### Remove a friend
DELETE http://localhost:8000/api/users/1/friends/2

### Remove a subject from a user
DELETE http://localhost:8000/api/users/1/subjects/4

### Search users
GET http://localhost:8000/api/users/search/test

